const $=s=>document.querySelector(s);const app=$('#app');
const modes={snooker:{name:'斯诺克',desc:'自由加分，记录单杆得分',max:147},eight:{name:'中式 8 球',desc:'适合局数或简易得分记录',max:8},chase:{name:'追分',desc:'设定目标分，领先即获胜',max:100},custom:{name:'自定义计分',desc:'自由设置，适合练习与友谊赛',max:null}};
let state=JSON.parse(localStorage.getItem('cue-score-state')||'null')||{screen:'home',mode:'snooker',count:2,players:[{name:'选手 1',avatar:''},{name:'选手 2',avatar:''}],scores:[0,0],turn:0,log:[],target:100};
const save=()=>localStorage.setItem('cue-score-state',JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function avatar(p,i){return p.avatar?`<img class="avatar" src="${p.avatar}" alt="${esc(p.name)}头像">`:`<div class="avatar avatar-letter">${esc((p.name||String(i+1))[0])}</div>`}
function render(){save();if(state.screen==='home')home();else if(state.screen==='setup')setup();else game()}
function home(){app.innerHTML=`<div class="hero"></div><section class="screen"><div class="brand">CUE SCORE · 台球记分</div><h1 class="home-title">一杆记分<br>专注每一次出杆</h1><p class="sub">为你的每一局，留下清晰又好看的记录。</p><button class="start" onclick="goSetup()">开始一局</button><div class="glass" style="padding:15px"><div class="brand" style="font-size:11px">选择比赛模式</div><div class="modes" style="margin-top:10px">${Object.entries(modes).map(([k,m])=>`<button class="mode" onclick="chooseMode('${k}')"><b>${m.name}</b><span>${m.desc}</span></button>`).join('')}</div></div></section>`}
function chooseMode(m){state.mode=m;state.screen='setup';render()}function goSetup(){state.screen='setup';render()}function backHome(){state.screen='home';render()}
function setup(){let m=modes[state.mode];app.innerHTML=`<section class="screen"><div class="topbar"><button class="back" onclick="backHome()">‹ 返回</button><span class="brand">新建对局</span></div><h1 class="setup-title">${m.name}</h1><div class="mode-pills">${Object.entries(modes).map(([k,v])=>`<button class="pill ${k===state.mode?'active':''}" onclick="chooseMode('${k}')">${v.name}</button>`).join('')}</div><div class="glass form-card"><label class="label">参赛人数</label><div class="stepper"><button onclick="changeCount(-1)">−</button><output>${state.count}</output><button onclick="changeCount(1)">＋</button><span class="sub">2–4 人</span></div>${state.mode==='chase'?`<label class="label">目标分</label><div class="stepper"><button onclick="changeTarget(-10)">−</button><output>${state.target}</output><button onclick="changeTarget(10)">＋</button><span class="sub">先到者胜</span></div>`:''}</div><div class="glass form-card"><div class="brand" style="font-size:11px">选手资料</div><div class="players">${state.players.slice(0,state.count).map((p,i)=>`<div class="player-edit">${avatar(p,i)}<input value="${esc(p.name)}" maxlength="12" oninput="rename(${i},this.value)" aria-label="选手姓名"><button class="photo-btn" onclick="pickPhoto(${i})">照片</button></div>`).join('')}</div></div><button class="primary" onclick="startGame()">开 球</button></section>`}
function changeCount(d){state.count=Math.max(2,Math.min(4,state.count+d));while(state.players.length<state.count)state.players.push({name:`选手 ${state.players.length+1}`,avatar:''});render()}function changeTarget(d){state.target=Math.max(10,state.target+d);render()}function rename(i,v){state.players[i].name=v;save()}let photoIndex=0;function pickPhoto(i){photoIndex=i;$('#photo-picker').click()}$('#photo-picker').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{state.players[photoIndex].avatar=r.result;render()};r.readAsDataURL(f);e.target.value=''};
function startGame(){state.scores=Array(state.count).fill(0);state.turn=0;state.log=[];state.screen='game';render()}function adjust(n){state.scores[state.turn]=Math.max(0,state.scores[state.turn]+n);state.log.unshift(`${state.players[state.turn].name} ${n>0?'+':''}${n} 分`);if(state.mode==='chase'&&state.scores[state.turn]>=state.target){render();setTimeout(results,80)}else render()}function nextTurn(){state.turn=(state.turn+1)%state.count;render()}function undo(){if(!state.log.length)return;let t=state.log.shift(),match=t.match(/([+−-]?\d+) 分$/);if(match){let i=state.players.findIndex(p=>t.startsWith(p.name));if(i>=0)state.scores[i]=Math.max(0,state.scores[i]-Number(match[1].replace('−','-')))}render()}
function game(){let leader=Math.max(...state.scores);let m=modes[state.mode];app.innerHTML=`<section class="screen"><div class="game-head"><button class="back" onclick="backHome()">‹ 退出</button><div class="game-mode">${m.name}${state.mode==='chase'?' · 目标 '+state.target:''}</div><button class="back" onclick="results()">结算</button></div><div class="table-decoration"><i class="ball b1"></i><i class="ball b2"></i><i class="ball b8"></i></div><div class="score-grid" style="--n:${state.count}">${state.players.slice(0,state.count).map((p,i)=>`<div class="glass score-card ${state.scores[i]===leader&&leader>0?'lead':''}">${avatar(p,i)}<div class="pname">${esc(p.name)}</div><div class="score">${state.scores[i]}</div>${i===state.turn?'<div class="turn">● 当前回合</div>':''}</div>`).join('')}</div><div class="quick">${[1,2,4,7,8,16,20,-1].map(n=>`<button onclick="adjust(${n})">${n>0?'+':''}${n}</button>`).join('')}<button class="wide" onclick="nextTurn()">下一位选手</button><button class="wide" onclick="adjust(-4)">撤回 4 分</button></div><div class="actions"><button onclick="undo()">↶ 撤销上一步</button><button class="end" onclick="results()">结束本局</button></div><div class="glass history"><h3>本局记录</h3>${state.log.length?state.log.slice(0,6).map(x=>`<div class="log">${x}</div>`).join(''):'<div class="empty">开始记分后，这里会显示每次得分。</div>'}</div></section>`}
function results(){let list=state.players.slice(0,state.count).map((p,i)=>({n:p.name,s:state.scores[i]})).sort((a,b)=>b.s-a.s);let modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-inner"><h2>本局结算</h2><p>${list[0].n} 获胜，精彩的一局。</p><div class="result-list">${list.map((x,i)=>`<div class="result"><span>${i===0?'🏆 ':''}${esc(x.n)}</span><b>${x.s} 分</b></div>`).join('')}</div><button class="close" onclick="this.closest('.modal').remove();backHome()">完成</button></div>`;document.body.append(modal)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');render();
